### ISSUE TITLE
Translate to Korean

### ISSUE THREAD

**Issue by WDever** [blockmatic/basilic#1]
Hi, I was very impressed by reading this repository and `hooks-architecture`

Actually, I'm Korean. So I translated this repository to Korean to read easily.

And I want to share it with another Korean developers.

Can I create pull request for adding korean version of `hooks-architecture`?

I wrote it in my own Notion workspace. https://www.notion.so/Hooks-Architecture-blockmatic-3127935cc9ab4acdbe4ecf41f6ae3491

I'll wait your reply!

**Comment by gaboesquivel** [comment]
Hi @WDever I'm sorry for the late reply, it's been a busy year. Yes, that would be awesome.

**Comment by WDever** [comment]
@gaboesquivel I'll improve the Korean version `hooks-architecture` and create a PR. Thanks! 👍

**Comment by WDever** [comment]
Hi @gaboesquivel
I'm so sorry but I'm too late. This repository's contents are changed. It is no longer about 'hooks-architecture'. It is about react-dapp-architecture and the README.md file changed a lot. So I can't translate. I'm so sorry. 😢

**Comment by gaboesquivel** [comment]
Thanks anyway @WDever. 

Yes, I no longer think putting all logic in context hooks is a great idea, I now prefer Zustand stores. Also I'm narrowing the scope of the repo web3 applications with react which is what we do. 

The previous version is available at https://github.com/blockmatic/react-dapp-architecture/tree/39a20c7caee895da56ea6487db9ca4c966c3e965
